CREATE TABLE customers (
    username VARCHAR(40) PRIMARY KEY
);
INSERT INTO customers VALUES ('student'), ('friend'), ('operator');

CREATE TABLE products (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price_cents BIGINT NOT NULL CHECK (price_cents > 0),
    stock INTEGER NOT NULL CHECK (stock >= 0)
);
-- Fictional products. These are not real purchases.
INSERT INTO products VALUES (1, 'Orbit headphones', 7900, 8);
INSERT INTO products VALUES (2, 'Pocket keyboard', 4500, 12);
INSERT INTO products VALUES (3, 'Study lamp', 3200, 5);

CREATE TABLE shop_orders (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(40) NOT NULL REFERENCES customers(username),
    request_key VARCHAR(80) NOT NULL,
    request_signature VARCHAR(150) NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 10),
    total_cents BIGINT NOT NULL CHECK (total_cents > 0),
    scenario VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'DECLINED', 'DEAD', 'CANCELLED')),
    attempts INTEGER NOT NULL DEFAULT 0,
    failures INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(username, request_key)
);
CREATE TABLE outbox (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL REFERENCES shop_orders(id),
    attempt INTEGER NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(order_id, attempt)
);
CREATE INDEX outbox_ready ON outbox(sent, due_at);
CREATE TABLE payments (
    order_id VARCHAR(36) PRIMARY KEY REFERENCES shop_orders(id),
    total_cents BIGINT NOT NULL,
    charged_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL REFERENCES shop_orders(id),
    message VARCHAR(300) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX events_by_order ON order_events(order_id, id);
